config/routes.rb
BnbTest::Application.routes.draw do
  resources :categories, only: :index
  resources :notes do
    put 'star', :on => :member, :as => 'star'
  end

  root to: 'home#index'
  match 'about', to: 'home#about', as: 'about'
  match 'install', to: 'home#install', as: 'install'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/category.rb
class Category
  include Mongoid::Document

  field :name

  has_many :notes

  default_scope asc(:name)
end

app/models/note.rb
class Note
  include Mongoid::Document
  
  field :title
  field :content
  field :star, type: Boolean, default: false

  belongs_to :category

  default_scope where(star: false).asc(:title)

  scope :starred, where(star: true)

  def category_name
    category.try(:name)
  end

  def category_name=(name)
    self.category = Category.find_or_create_by(name: name) if name.present?
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  field :provider
  field :uid
  field :name
  field :email
  field :photo

  def self.from_omniauth(auth)
    where(auth.slice('provider', 'uid')).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.email = auth['info']['email']
      user.photo = auth['info']['image']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authenticate_user!
    if !current_user
      redirect_to root_path, error: "Please log in to use this app"
    end
  end
  
  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @categories = Category.where(name: /#{params[:term]}/i)

    respond_to do |format|
      format.json { render json: @categories.map(&:name) }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def install
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!

  # GET /notes
  def index
    @starred = Note.starred
    @categories = Category.all

    respond_to do |format|
      format.html
    end
  end

  # GET /notes/1
  def show
    @note = Note.unscoped.find(params[:id])

    respond_to do |format|
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  def new
    @note = Note.new

    respond_to do |format|
      format.html
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.unscoped.find(params[:id])
  end

  # POST /notes
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /notes/1
  def update
    @note = Note.unscoped.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # PUT /notes/1/star
  def star
    @note = Note.unscoped.find(params[:id])
    @note.update_attributes(params[:note])

    @starred = Note.starred
    @categories = Category.all
    render partial: 'side'
  end

  # DELETE /notes/1
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    @starred = Note.starred
    @categories = Category.all
    respond_to do |format|
      format.html { render partial: 'side' }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to notes_path, notice: "Logged in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_nav.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href="#") Bits n Bytes
      .container.nav-collapse
        %ul.nav
          - if current_user
            %li.dropdown
              %a.dropdown-toggle{:href => '#', :data => {:toggle => 'dropdown'}}
                Notes
                %b.caret
              %ul.dropdown-menu
                %li= link_to 'Preview', notes_path
                %li= link_to 'Add a Note', new_note_path
          = yield(:nav) if content_for(:nav)
          %li= link_to 'About', about_path
        %ul.nav.pull-right
          %li= link_to 'Install App', install_path
          - if current_user
            %li.divider-vertical
            %li.dropdown
              %a.dropdown-toggle{:href => '#', :data => {:toggle => 'dropdown'}}
                = current_user.name
                %b.caret
              %ul.dropdown-menu
                %li= link_to 'Logout', logout_path

app/views/categories/_category.html.haml
%li.nav-header= category.name
= render category.notes

app/views/categories/_form.html.haml
= form_for @category do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/home/about.html.haml
%h1 Home#about
%p Find me in app/views/home/about.html.haml

app/views/home/index.html.haml
.hero-unit.welcom
  %header
    %h1 Bits n Bytes
    %p A notes template management app.
  - unless current_user
    = link_to "Login with Google", '/auth/google_oauth2', class: 'btn btn-large btn-primary'

app/views/home/install.html.haml
%header.hero-unit
  %h1 Install App
%p In order to use the Copy feature in Chrome, you will need to install this Chrome App.
%p
  %a.btn.btn-primary{href: '/bits-n-bytes.crx'} Install Chrome App
%p Support of other browsers coming soon.

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Bits n Bytes
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    = render 'nav'
    .container
      - flash.each do |name, msg|
        - case name
        - when :notice
          .alert.alert-success
            %button.close{:data => {:dismiss => 'alert'}} x
            %strong Awesome!
            = msg
        - when :error
          .alert.alert-error
            %button.close{:data => {:dismiss => 'alert'}} x
            %strong Oh snap!
            = msg
            
      .content
        = yield

      %footer
        %p &copy; TJ Coding 2012
    = javascript_include_tag "application"

app/views/notes/_form.html.haml
= simple_form_for @note, html: {class: 'form-horizontal'} do |f|
  = f.input :category_name, as: :autocomplete, source: categories_path
  = f.input :title
  = f.input :star, :as => :boolean, :label => false, :inline_label => "Star this note?"
  = f.input :content, :as => :text
  = f.button :submit

app/views/notes/_note.html.haml
%li{:data => {:id => note.id}}
  .btn-group
    = link_to note, :class => 'delete btn btn-mini btn-danger', :data => {:remote => true, :confirm => 'Are you sure?', :method => 'delete', :type => 'html', :target => '#notes'} do
      %i.icon-trash
      delete
    = link_to edit_note_path(note), :class => 'edit btn btn-mini btn-info' do
      %i.icon-edit
      edit
    = link_to star_note_path(note), :class => 'star btn btn-mini', :data => {:remote => true, :method => 'put', :type => 'html', :params => "note[star]=#{!note.star}", :target => '#notes'} do
      %i{:class => note.star ? 'icon-star' : 'icon-star-empty'}
    = link_to note.title, note, :class => 'show btn btn-mini btn-success', :title => note.title, :data => {:remote => true, :target => '#description', :type => 'json'}

app/views/notes/_side.html.haml
%li.nav-header Starred
= render @starred
= render @categories

app/views/notes/edit.html.haml
%header.hero-unit
  %h1 Editing #{@note.title}

= render 'form'

= link_to 'Back', notes_path

app/views/notes/index.html.haml
.row-fluid.show-grid
  .well.span4
    = link_to new_note_path, class: 'btn btn-primary' do
      %i.icon-plus.icon-white
      Add a Note
    %h3 Notes
    %ul.nav.nav-list#notes
      = render 'side'
  .span8
    %header.hero-unit
      %h1 Preview
    .sub-nav
      %ul.nav.nav-pills
        %li.btn-group
          %button.btn.btn-primary#copy{:data => {:target => '#description'}} Copy
        %li.btn-group
          %button.btn#clear{:data => {:target => '#description'}} Clear
    %pre#description

app/views/notes/new.html.haml
%header.hero-unit
  %h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @note.title
%p
  %b Content:
  = @note.content
%p
  %b Star:
  = @note.star

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path